---
abstract: 'format PseudoPod as valid XHTML'
author:
  - 'Alan Young <alansyoungiii@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::NoWarnings: 0
  Test::Perl::Critic::Progressive: 0
  Try::Tiny: 0
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-PseudoPod-XHTML
requires:
  Carp: 0
  Pod::PseudoPod::HTML: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/harleypig/Pod-PseudoPod-XHTML/issues
  repository: git://github.com/harleypig/Pod-PseudoPod-XHTML.git
version: 1.03
x_BuiltWith:
  modules:
    Carp: 1.11
    ExtUtils::MakeMaker: 6.59
    File::Temp: 0.22
    Module::Build: 0.38
    Pod::PseudoPod::HTML: 0.18
    Scalar::Util: 1.23
    Test::More: 0.98
    Test::NoWarnings: 1.03
    base: 2.15
    perl: 'NA(skipped: perl)'
    strict: 1.04
    warnings: 1.06
  perl:
    original: v5.10.1
    qv: 1
    version:
      - 5
      - 10
      - 1
  platform: linux
